### ISSUE TITLE
HTTP Status 405 - HTTP method GET is not supported by this URL

### ISSUE THREAD

**Issue by vanluot** [vianneyfaivre/liferay-spring-rest-portlet#1]
When I call service url, application display "HTTP Status 405 - HTTP method GET is not supported by this URL". I use Liferay 6.1.0 CE, server tomcat

**Comment by vianneyfaivre** [comment]
what URL are you calling ? 
is your controller method configured with RequestMethod.GET ?

**Comment by vanluot** [comment]
Thanks for your feedback,
I configured method with RequestMethod.GET in LiferayRestController class
        @RequestMapping(value = "/users", method = RequestMethod.GET)
	@ResponseStatus(HttpStatus.OK)
	public List<UserBean> getUsers(HttpServletRequest request) throws SystemException {...}
Then I use javascript to test, my project name is restful-portlet
<script>
	var request = new XMLHttpRequest();
	var url = "/restful-portlet/services/users";

	alert("Before calling "+url);
	
	request.open("GET", url, true);
	request.send();
	request.onreadystatechange = function() {
		if(request.readyState == 4) {
			alert("After calling "+url);
			document.getElementById("result").innerHTML = request.responseText;
		}
	};
</script>

https://github.com/vanluot/restful-portlet
